name: LootLoop
version: '1.0-SNAPSHOT'
main: be.artex.lootLoop.LootLoop
api-version: '1.21.11'
commands:
  sell:
    description: "sell"
    usage: "/sell"
  test:
    description: "gives any item"
    usage: "/test <item-id>"
